version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: maxway_toliq
      POSTGRES_USER: maxway_admin
      POSTGRES_PASSWORD: ozodbek2006

  web:
    build: .
    command: >
      bash -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --no-input &&
        python3 manage.py init_superuser &&
        gunicorn --reload -b 0.0.0.0:8000 config.wsgi --workers 1 --timeout 300 --log-level DEBUG
      "
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_NAME: maxway_toliq
      DB_USER: maxway_admin
      DB_PASSWORD: ozodbek2006
      DB_HOST: db
      DB_PORT: 5432
